export const translateName = {
  buildings: "Недвижимость",
  work: "Работа",
  technic: "Электроника",
  transport: "Транспорт",
  forHouse: "Для дома и дачи",
  services: "Услуги",
  clothes: "Одежда, обувь и аксессуары",
  forBusiness: "Для бизнеса",
  beautyHealth: "Красота и здоровье",
  forKids: "Товары для детей",
  pets: "Животные",
  habbits: "Хобби и отдых",
  handmade: "Ручная работа",
  floors: "Квартиры",
};
