export default [
  {
    id: 1,
    title: "Аренда квартиры 1",
    place: "Батуми",
    img: "",
    price: 700,
    priceName: "$",
    languages: ["rus", "eng"],
    category: "buildings",
  },
  {
    id: 2,
    title: "Аренда квартиры 2",
    place: "Батуми",
    img: "",
    price: 300,
    priceName: "$",
    languages: ["rus", "eng"],
    category: "buildings",
  },
  {
    id: 3,
    title: "Аренда квартиры 3",
    place: "Батуми",
    img: "",
    price: 500,
    priceName: "Р",
    languages: ["rus", "eng"],
    category: "buildings",
  },
  {
    id: 4,
    title: "Аренда квартиры 4",
    place: "Батуми",
    img: "",
    price: 1000,
    priceName: "$",
    languages: ["rus", "eng"],
    category: "buildings",
  },
  {
    id: 5,
    title: "Аренда квартиры 3",
    place: "Батуми",
    img: "",
    price: 500,
    priceName: "Р",
    languages: ["rus", "eng"],
    category: "buildings",
  },
];
